package application.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.scene.layout.VBox;
import javafx.event.ActionEvent;

public class menuController {
    
	@FXML
	private Button cellComponentBtn;
	@FXML
	private Button cellDivisionBtn;
	@FXML
	private Button helpBtn;
	@FXML
	private Button quitBtn;

	// Event Listener on Button[#cellDivisionBtn].onAction
	@FXML
	public void cellDivPressed(ActionEvent event) {
		// TODO Autogenerated
	}

	public void menuController() {}
}
